---
# tasks file for freeswitch-mw
#- name: Add FreeSwitch apt repository (1.4)
#  apt_repository: repo='deb http://files.freeswitch.org/repo/deb/debian/ wheezy main'

#- name: Add FreeSwitch Repo Signing key
#  apt_key: url=http://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub

#- name: Install FreeSwitch server
#  action: apt name=freeswitch-meta-vanilla update_cache=yes

# Installation from sources
- name: Install FreeSwitch dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
   - autoconf
   - automake
   - devscripts
   - gawk
   - g++
   - git-core
   - libjpeg-dev
   - libncurses5-dev
   - libtool-bin
   - make
   - python-dev
   - gawk
   - pkg-config
   - libtiff5-dev
   - libperl-dev
   - libgdbm-dev
   - libdb-dev
   - gettext
   - libssl-dev
   - libcurl4-openssl-dev
   - libpcre3-dev
   - libspeex-dev
   - libspeexdsp-dev
   - libsqlite3-dev
   - libedit-dev
   - libldns-dev
   - libpq-dev

- name: Install FreeSwitch source code
  git: repo=https://freeswitch.org/stash/scm/fs/freeswitch.git
       dest=/usr/src/
       vesrion=v1.4

- name: bootstrap
  command: /usr/src/freeswitch/bootstrap.sh -j

- name: copy template modules file
  copy: src=../templates/modules.conf dst=/usr/src/freeswitch/modules.conf backup=yes

- name: Freeswitch configuration
  command: /usr/src/freeswitch/configure

- name: FreeSwitch make
  command: /usr/src/freeswitch/make

- name: FreeSwitch install
  command: /usr/src/freeswitch/make install

- name: FreeSwitch insrall sounds
  command: /usr/src/freeswitch/make cd-sounds-install cd-moh-install

- name: Add user "freeswitch"
  user: name=freeswitch groupe=daemon home=/usr/local/freeswitch

- name: Change ownership of FreeSwitch installation
  file: path=/usr/local/freeswitch/ owner=freeswitch group=daemon mode="ug=rwX,o=" state=directory recurse=yes

- name: Change ownership of FreeSwitch binary files
  file: path=/usr/local/freeswitch/bin/ owner=freeswitch group=daemon mode="u=rwx,g=rx" state=directory recurse=yes

- name: Create /var/lib/freeswitch
  file: path=/var/lib/freeswitch owner=freeswitch group=daemon mode="u=rwx,o=" state=directory recurse=yes

- name: copy init script
  copy: src=../templates/freeswitch.init dst=/etc/init.d/freeswitch

- name: Change ownership of FreeSwitch init script
  file: path=/etc/init.d/freeswitch owner=freeswitch group=daemon mode="+x"

- name: update init scripts
  command: update-rc.d freeswitch defaults

- name: cli link
  file: src=/usr/local/freeswitch/bin/fs_cli dest=/bin/fs_cli state=link