# tasks file for Debian flavour

- name: Add FreeSwitch Repo Signing key
  apt_key: url=https://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub state=present

- name: Add FreeSwitch apt repository (1.6) (Debian 8/Jessie)
  apt_repository:
    repo: deb http://files.freeswitch.org/repo/deb/freeswitch-1.6/ jessie main
    state: present
    filename: 'freeswitch'

- name: Update APT Cache
  apt: update_cache=yes

- name: Ensure tzdata is installed
  apt: name=tzdata state=latest
  when: ntp_install

### source of systemd-timesynd : https://github.com/debops/ansible-ntp
- name: Ensure that alternative daemons/programs are not installed
  apt:
    name: '{{ item }}'
    state: absent
    purge: True
  with_flattened:
    - ntpdate
    - ntp
    - openntpd
  when: ntp_install

- name: Manage systemd-timesyncd state
  service:
    name: 'systemd-timesyncd'
    state: started
    enabled: True
  when: ntp_install

# Configure systemd-timesyncd
- name: Include systemd-timesyncd configuration
  include: systemd-timesyncd.yml
  when: ntp_install

- name: Timezone configuration
  include: timezone.yml
  when: (ntp_timezone|d() and ntp_install)

# Install unbound
- name: Include unbound installation / configuration
  include: unbound.yml
  when: unbound_install

# Install FreeSwitch
- name: Install FreeSwitch
  apt: name={{ item }} state=present
  with_items: "{{ freeswitch_packages }}"

#- name: Copy FreeSwitch config after back up default one
#mv /etc/freeswitch /etc/freeswitch.orig
#mkdir /etc/freeswitch
#cp -R /var//resources/templates/conf/* /etc/freeswitch

# sngrep
- name: mod_bcg729 codec installation process
  include: g729.yml
  when: freeswitch_g729_install

# mod_fail2ban
# https://freeswitch.org/confluence/display/FREESWITCH/Fail2Ban
# https://freeswitch.org/confluence/display/FREESWITCH/mod_fail2ban
- name: install fail2ban
  apt: name=fail2ban state=latest
  when: fail2ban_install == true

- copy: src={{ fail2ban_local_jail }} dest={{ fail2ban_local_jail_file }}
  when: fail2ban_install == true
- copy: src={{ fail2ban_fs }} dest={{ fail2ban_filter_dir }}/freeswitch.conf
  when: fail2ban_install == true
- copy: src={{ fail2ban_dos_fs }} dest={{ fail2ban_filter_dir }}/freeswitch-dos.conf
  when: fail2ban_install == true

# monit

# munin
- name: check if munin-node is installed
  apt: name=munin-node state=latest
  register: apt_munin_node_check
  ignore_errors: yes

- include: munin-plugin.yml
  when: apt_munin_node_check.rc == 0

# sngrep
- name: Sngrep installation process
  include: sngrep.yml
  when: sngrep_install

